### ISSUE TITLE
This repo needs a README 

### ISSUE THREAD

**Issue by munkm** [munkm/2024-06-summerschool-paper#2]
I was very bad by not adding one immediately

**Comment by joey-kilgore** [comment]
Maybe we could include a link to the main URSSI page for this teaching session to give a reference to what the purpose of this repo is?
https://github.com/si2-urssi/summerschool-June2024

**Comment by munkm** [comment]
That's a great point @joey-kilgore ! Would you mind opening another issue for that suggestion? We have a readme now so this issue is going to close. 

This issue is resolved by #4
